---
#############################################################################
#      0) Взять секреты из vault и добавить SSH ключи в known_hosts         #
#############################################################################

- name: Pull secrets from vault
  hosts: all
  gather_facts: false
  tags:
    - always
  roles:
    - role: bmstu.vats.init

#############################################################################
#                 1) Установка общесистемного ПО                            #
#############################################################################

- name: Install docker and neccessary packages
  hosts: all
  tags:
    - install_docker
  roles:
    - role: bmstu.vats.install_docker

#############################################################################
#                   2) Инициализация Docker Swarm                           #
#############################################################################

- name: Initialize docker swarm
  hosts: managers
  tags:
    - docker_swarm
  roles:
    - role: bmstu.vats.docker_swarm
      role_action: init

- name: Join workers to the swarm
  hosts: workers
  tags:
    - docker_swarm
  roles:
    - role: bmstu.vats.docker_swarm
      role_action: join

#############################################################################
#   3) Получение сертификатов с настройкой автоматического обновления       #
#############################################################################

- hosts: all
  tags:
    - obtain_certs
  become: true
  vars:
    certbot_install_method: package

    certbot_auto_renew:        yes
    certbot_auto_renew_user:   "root"
    certbot_auto_renew_hour:   "3"
    certbot_auto_renew_minute: "30"
    certbot_auto_renew_options: "--quiet"
    
    certbot_create_if_missing: yes
    certbot_create_method:     "standalone"
    certbot_hsts:              yes
    certbot_admin_email:       "{{ secrets.admin_email }}"
    
    certbot_testmode: no
    
    certbot_certs:
      - domains:
          - "{{ secrets.server_name }}"

    certbot_create_standalone_stop_services:
      - docker

  roles:
    - geerlingguy.certbot

